### ISSUE TITLE
Improve testing on formatting of Metrics object

### ISSUE THREAD

**Issue by glenn-m** [glenn-m/promR#10]
Currently we have few tests around the formatting of the metrics output from Prometheus, this should be improved.

We should also avoid having a reliance on external systems for the tests. Perhaps we can create a data set for use in testing?

[test-metrics-format.R](https://github.com/glenn-m/promR/blob/master/tests/testthat/test-metrics-format.R)

**Comment by konradzdeb** [comment]
So, I've generated data set for testing like that:

```r
library(curl)
library(httr)
cfm_output <- NULL
trace(
  curl_fetch_memory,
  exit = function() {
    cfm_output <<- returnValue()
  }
)
host = "http://demo.robustperception.io"
port = 9090
params <- list(NULL)
response <- GET(paste0(c(host, ":", port, "/api/v1/query_range"), collapse = ""),
                query = params)
# So this supposed to be this mock response
save(cfm_output, file = "tests/testthat/instant_query_response.rda")
```

This flows from the page you have shared with me and is now in commit https://github.com/konradzdeb/promR/commit/3e85f35bfdb9fed80f2a76097b649d789a3c274d I'll see if that lends itself well for tests. I've added `mockr` as a dependency.

**Comment by konradzdeb** [comment]
I reckon this will require more work to be solutioned properly, as can't just easily port [the example](https://www.mango-solutions.com/blog/testing-without-the-internet-using-mock-functions).

```
test-response-check.R:83: warning: Check that class functions source data.
with_mock() cannot mock functions defined in other packages.

test-response-check.R:83: error: Check that class functions source data.
curl_fetch_memory not found in environment promR.
1: mockr::with_mock(`curl::curl_fetch_memory` = function(...) {
       load("instant_query_response.rda")
       cfm_output
   }, prom$query(query = "go_goroutines", 
       time = as.numeric(as.POSIXct(Sys.time())))) at /Users/huski/Documents/R Projects/promR/tests/testthat/test-response-check.R:83
2: with_mock_(.dots = .dots, .parent = .parent, 
       .env = .env)
3: create_mock_env_(.dots = get_mock_dots(dots), 
       .env = .env, .parent = .parent)
4: extract_new_funcs_(dots, .env)
5: extract_mocks(dots = dots, env = .env)
6: lapply(stats::setNames(nm = names(dots)), 
       function(qual_name) extract_mock(qual_name, 
           dots[[qual_name]], env))
7: FUN(X[[i]], ...)
8: extract_mock(qual_name, dots[[qual_name]], 
       env)
9: check_mock(name, env)
10: stopc(name, " not found in environment ", 
       environmentName(env), ".")
11: stop(..., call. = FALSE, domain = NA)
──────────────────────────────
```

---
*Note:*

- [ ] Add [setup-....R](https://www.tidyverse.org/articles/2017/12/testthat-2-0-0/)  and `teardown-xyz.R` to properly set up test environments.

**Comment by konradzdeb** [comment]
Hi @glenn-m,

A quick question, as per [mockr](https://github.com/krlmlr/mockr):

> If you need to mock an external function, write a wrapper.

I've written a simple wrapper that can be tested. I reckon that re-created response object may now work with this. Does that make sense to you? Side note, we will be creating wrapper functions for all the stuff that should be tested? I reckon it's not that much but documentation and examples on that are scarce. *Maybe* using stubs from `mockery` package would be "cleaner" as per [this chat](https://stackoverflow.com/a/50448186/1655567).

https://github.com/konradzdeb/promR/blob/825d1a98b764575a3cf10b99283399997f8f3f02/R/utils.R#L55-L61

**Comment by glenn-m** [comment]
Yes, we'll need to use some combination of mocking and stubs. Where the stubs will return pre-canned API responses.

I don't think mockr has stubbing built-in, but [mockery](https://github.com/jfiksel/mockery) does.
