### ISSUE TITLE
Uninformative error messages on wrong timespan

### ISSUE THREAD

**Issue by konradzdeb** [glenn-m/promR#13]
# Problem
The when running sample code:
https://github.com/glenn-m/promR/blob/13faf82a09e54d1b6baee00714f907f11598d159/README.Rmd#L32-L34
the query would return data frame with 0 rows:
```r
metrics_current <- prom$query(query = "go_goroutines", 
                              time = format(Sys.time(),  "%Y-%m-%dT%H:%M:%SZ"))
# Error in format_metrics_current_data(metrics) : 
#  Assertion on 'x' failed: Must have at least 1 rows, but has 0 rows.
metrics_current <- prom$query(query = "go_goroutines", 
                             time = format(Sys.time() - 10,  "%Y-%m-%dT%H:%M:%SZ"))
 # Error in format_metrics_current_data(metrics) : 
 #  Assertion on 'x' failed: Must have at least 1 rows, but has 0 rows.
```
for:

```r
Sys.time()
# [1] "2019-04-01 07:22:00 BST"
```

the data would be produced for `Sys.time() - 3600`

```r
metrics_current <- prom$query(query = "go_goroutines", 
                               time = format(Sys.time() - 3600,  "%Y-%m-%dT%H:%M:%SZ"))
```

It's unclear whether:
 * there is no data for the period corresponding to `07:22` but there is for an hour earlier (?) `Sys.time() - 3600` 
 * the connection failed
 * query failed

# Suggested resolution

## For internet connection

If possible to solve through #11 if not consider running `curl::has_internet()` before query, return stop
```r
if (!curl::has_internet()) stop("This machine is not connected to the Internet :)")
```

## For query

Shall return something like (?):

> The query completed but returned no data....

---
Potentially related to #11

**Comment by glenn-m** [comment]
I've also found that using `format(Sys.time() - 10,  "%Y-%m-%dT%H:%M:%SZ")` is less reliable than passing in a unix timestamp, i.e. `as.numeric(as.POSIXct(Sys.time()))`

**Comment by konradzdeb** [comment]
Agreed, that’s definitely better. Also format changes class to character, which I reckon, may be not ideal in the context of creating xts objects in future...

--
Konrad

**Comment by konradzdeb** [comment]
Hi,

Before I start, just to clarify what would be the right approach to solve this.

# Desired behaviour scenarios

1. **`metrics` object has no rows**
 error message stating the above
 *- or -*
 a warning message indicating that the returned object is empty

2. **Query failed to run**
 error message surfacing API message on why the query failed to run
 *- or -*
 warning message with the above?

3. **No internet connection / wrong host**
 error message stating the above
 *- or  -*
 warning message with the above?

4. Any other scenario?

# Testing strategies

1. Generate wrong replies via `with_mock` and check if error messages are surfaced as desired
*- or-*
2. Run tests only when connected and host accessible (probably less reliable)

**Comment by glenn-m** [comment]
@konradzdeb I'm kind of the opinion that all of the above scenarios should generate an error as opposed to a warning. But I'm happy to hear any counter-arguments 

I'd suggest we use mocks for the testing however, as we don't want to be tied to an external service for our tests.

**Comment by konradzdeb** [comment]
Agreed on both points :) 

Maybe one point to consider, is it possible to have a situation where it’s legitimate that returned data frame will be empty? I’m thinking of this being used to automatically update some reports with Prometheus data on odd hours or for small ranges where no data would be captured, is this possible? In that case, returning error may force folk to use tryCatch if their scripts to keep on running event on empty data. If there always should be some data, then I agree that error is better.

--
Konrad

**Comment by glenn-m** [comment]
@konradzdeb There might not always be Data, if you query a timeframe without data then Prometheus just returns an empty JSON array. So you could check for that possibly.

Maybe no data just returns a warning then and the rest are errors? My only worry is the warnings not being caught by users. How do other R packages behave?

**Comment by konradzdeb** [comment]
> How do other R packages behave?

So this is an interesting point. I had a look at the `Quantmod` package that offers access to number of finance data. 

# Working example

```r
# Generate some sample quantmod errors
library(quantmod)

# Set where to look for symbols
setSymbolLookup(AAPL = 'yahoo',
                CYBG.L = 'yahoo')

# Get symbols including wrong symbol
getSymbols(c('AAPL', 'CYBG.L'))


ls()
# AAPL and CYBG.L objects are created in parent env.
```

# Errors

## Wrong symbol
 
Warning on first attempt, error on second.

```r
>> setSymbolLookup(BSBS = 'yahoo')
>> getSymbols('BSBS')
Warning: BSBS download failed; trying again.
Error: BSBS download failed after two attempts. Error message:
HTTP error 404.
```

## Wrong `to` time

```r
# Wrong time in the future
getSymbols(Symbols = 'AAPL',
           from = Sys.Date() - 10,
           to = Sys.Date() + 100)
```

will get an `xts` object for existing dates only

```r
>> index(AAPL)
[1] "2019-03-25" "2019-03-26" "2019-03-27" "2019-03-28" "2019-03-29" "2019-04-01"
[7] "2019-04-02" "2019-04-03"
```

## Wrong `from` and `to`

Warning and error

```r
getSymbols(Symbols = 'AAPL',
           from = Sys.Date() + 10,
           to = Sys.Date() + 20)
# Warning: AAPL download failed; trying again.
# Error: AAPL download failed after two attempts. Error message:
# HTTP error 400.
```

So the rough conclusion would be, *if there is anything then return something; if there is nothing then error*. Shall we take a similar approach?  

---
The warning/repeat concept is interesting and we didn't think of that. Personally, I've mixed feelings as on the one hand folk could be expected to wrap calls using [`invokeRestart`](http://adv-r.had.co.nz/beyond-exception-handling.html). On the other hand, it's not quickest thing to do so it's not necessarily a bad thing if the package provides some option to try a few times and error on *n-th* attempt.

**Comment by glenn-m** [comment]
Personally for simplicity's sake I'd leave out the retry functionality for now. 

The way Prometheus works is that if there's a data point between the `start` & `end` it will return it. So the only scenario you won't get a single row is:

1.  When there's something wrong with your query, which I've handled in surfacing Prometheus errors. 
2. There's genuinely no data.

So I think if nrow < 1 you can safely surface a warning stating there's no data points.

**Comment by konradzdeb** [comment]
So had a look at what's being send for a wrong date.
```r


# Set-up ------------------------------------------------------------------

library(promR)
prom <-
    Prometheus$new(host = "http://demo.robustperception.io", port = 9090)

trace(
    # Change to curl fetch memory
    what = httr::GET,
    exit = function() {
        get_results_OK <<- returnValue()
    }
)

metrics_instant_OK <-
    prom$query(query = "go_goroutines", time = as.POSIXct(Sys.time() - 60))


# Wrong period ------------------------------------------------------------

trace(
    # Change to curl fetch memory
    what = httr::GET,
    exit = function() {
        get_results_WRONG <<- returnValue()
    }
)

# Will throw an error but get_results_WRONG is generated as needed
metrics_instant_WRONG <-
    prom$query(query = "go_goroutines", time = as.POSIXct(Sys.time() + 3600))

# Compare -----------------------------------------------------------------

# Create basic comparison object
res_comp <- compare::compare(model = get_results_OK,
                             comparison = get_results_WRONG)

# What differs
as.data.frame(res_comp$detailedResult)
# res_comp$detailedResult
# FALSE == difference
# url                           FALSE
# status_code                    TRUE
# headers                       FALSE
# all_headers                   FALSE
# cookies                        TRUE
# content                       FALSE
# date                           TRUE
# times                         FALSE
# request                       FALSE
# handle                         TRUE

# Details
# both 200
get_results_OK$status_code
get_results_WRONG$status_code

get_results_OK$headers$`content-length`
# 233
get_results_WRONG$headers$`content-length`
# 87
```

It seems that query passes and runs, with both wrong and correct time returning the same status code. Wrong time will return data frame with no rows, here is where we are capturing an error via `checkmate`, without:
https://github.com/glenn-m/promR/blob/edf01c850fa1f9d813aed67582ea901558cd657b/R/format_metrics_data.R#L8-L10
It would run and fail on non-existent column names being referenced. 

A potential solution would be to simply check resulting data frame and if empty, return an error message saying that no data meet criteria, i.e. timespan is wrong. A potentially better solution would be not to create a data frame in that case. I would suggest adding that in `response_check`. It could check objects that are referenced later and return a custom error message if empty:
https://github.com/glenn-m/promR/blob/cfdda174371471b7e78dcb8b8b533c0403a45f12/R/promR.R#L51-L54

Not the cleanest solution but from this initial look nothing that is passed from `GET` seems to point to an error with the timestamp.

**Comment by glenn-m** [comment]
@konradzdeb If we add it into response_check we'll have to parse the JSON to assert that it holds no rows. So I'm thinking we perhaps add a check after L53?

https://github.com/glenn-m/promR/blob/cfdda174371471b7e78dcb8b8b533c0403a45f12/R/promR.R#L51-L54

**Comment by konradzdeb** [comment]
True, after L53 possibly cleaner than parsing JSON twice.
