### ISSUE TITLE
Protect  end-users from passing nonsensical timeout values?

### ISSUE THREAD

**Issue by konradzdeb** [glenn-m/promR#2]
On that
https://github.com/glenn-m/promR/blob/d5c1de047c0fbb8208677e2b5373372fdb2c29d3/R/promR.R#L32-L39
I was now thinking, is this `timout` in seconds? If so maybe it's good to add [`checkmate::assertInt`](https://rdrr.io/cran/checkmate/man/checkInt.html) to avoid people passing `-10` as `is.null` won't protect from not sure. Not sure how *defensive*<sup>1</sup> you want that script to be and whether it's worth the effort...

---

<sup>1</sup>[checkmate: Fast Argument Checks for Defensive R Programming](https://arxiv.org/abs/1701.04781)

**Comment by glenn-m** [comment]
[`timeout`](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) is in the form of `10s`, `5s` etc. It's probably a good idea, but I don't think it's possible to `checkmate::assertInt` due to it having the unit character. 

We could possibly split it, assert the number isn't negative then join it back together?

**Comment by konradzdeb** [comment]
Yes, could be done like that. Or something with lubridate checking for [seconds](
https://stackoverflow.com/a/13791148/1655567)? But I think that your idea is better...

**Comment by konradzdeb** [comment]
Maybe something on those lines:
https://github.com/konradedgar/promR/blob/5f7ba0a88856e93813e221f4a71988813c05d63a/R/promR.R#L40-L54

**Comment by glenn-m** [comment]
Problem with that is that timeout can be like `10s` `5m` `2h`.  I should have mentioned that earlier!

**Comment by tylerlittlefield** [comment]
In that case, what about something like:

```r
x <- "1.5s"
y <- "1.5m"
z <- "1.5h"

time_examples <- c(x, y, z)

parse_timeout <- function(timeout_val) {
  
  # If timeout starts with '-' stop the function and inform the user
  if(startsWith(timeout_val, "-"))
    stop("Can't use negative timeout values, please use a positive number.", call. = FALSE)
  
  # Identify the time unit
  time_unit <- sub("[^[:alpha:]]+", "", timeout_val)
  
  # Test if the time_unit > 1 or == 0. If it's the former, we assume they gave
  # something like 'minutes' instead of 'm'. If it's the latter, we assume they
  # didn't give any unit at all, e.g. '1.5'.
  if(nchar(time_unit) > 1 | nchar(time_unit) == 0) 
    stop("Couldn't identify timeout value. Please use 's', 'm', or 'h'", call. = FALSE)
  
  # Negation of %in% operator to test if time_unit is one of the three options
  `%nin%` = Negate(`%in%`)
  
  # If time_unit isn't in one of the three options, stop the function
  if(time_unit %nin% c("s", "m", "h"))
    stop("Timeout must be in seconds 's', minutes 'm', or hours 'h'.", call. = FALSE)
  
  # If the time_unit is identified, assign a conversion value so all timeouts
  # are measured in seconds.
  if(time_unit == "s") conversion <- 1
  if(time_unit == "m") conversion <- 60
  if(time_unit == "h") conversion <- 3600
  
  # Remove all non numerics, keep '.', convert to numeric and multiply by conversion value
  timeout_seconds <- as.numeric(gsub("[^0-9.]", "", timeout_val)) * conversion
  
  return(timeout_seconds)
  
}

sapply(time_examples, parse_timeout)

#>  1.5s   1.5m   1.5h 
#>   1.5   90.0 5400.0 
```

**Comment by glenn-m** [comment]
Thanks for weighing in @tyluRp 

 I'd say that looks like a good solution!  If you'd like to, feel free to submit a PR.
