### ISSUE TITLE
Metrics data formatting function

### ISSUE THREAD

**Issue by konradzdeb** [glenn-m/promR#21]
With respect to the object that is returned here:
https://github.com/glenn-m/promR/blob/aad57015d5029949a261ca0e30348dcf34ac0d68/R/promR.R#L134-L142

Is the generated data frame of similar format that is handled by the function that formats metrics for ranges and instant query? If so a potential solution could be to devise one generic function that formats all data frame outputs returned by Prometheus, irrespectively of the query. If you haven’t started on that, I’m happy to progress this (assuming that this is the right approach, of course)

https://github.com/glenn-m/promR/blob/aad57015d5029949a261ca0e30348dcf34ac0d68/R/format_metrics_data.R#L28-L65

**Comment by glenn-m** [comment]
I don’t think we will be able to have one function that does everything, but we will be able to modularise some bits and pieces.

**Comment by glenn-m** [comment]
Might be worthwhile including #26 in this?

**Comment by konradzdeb** [comment]
> Might be worthwhile including #26 in this?

Yes, it makes perfect sense to close those two issues in the same fix.

**Comment by konradzdeb** [comment]
I kind of reckon that we have merged that so I'm voting to close this (unless I'm wrong)...
