### ISSUE TITLE
Ensure value column is cast as a reasonable type

### ISSUE THREAD

**Issue by glenn-m** [glenn-m/promR#26]
Currently, it seems the value column is being cast as a `character` type, meaning users have to cast to `complex` or `numeric`. 

```R
library(promR)
library(ggplot2)
prom <- Prometheus$new(host = "http://demo.robustperception.io", port = 9090)
metrics_instant <- prom$query(query = 'go_goroutines', time = as.POSIXct(Sys.time() - 60))
m <- ggplot(metrics_instant, aes(metrics_instant$job)) + 
  geom_bar(aes(weight=as.complex(metrics_instant$value))) +
  xlab("Prometheus Jobs") +
  ylab("Value")
plot(m)
```

Ideally this should be handled for the user as the value column will always be a numerical value.

However, some Prometheus metrics will return scientific notation when the value is large enough. 

For example:
`alertmanager_silences_query_duration_seconds_bucket{le="2.5"} 4.766468e+06`

Is there any reason we shouldn't just cast everything to the `complex` type? Or would it be better to default to `numeric` unless `complex` is required? What's your opinion @konradzdeb?

**Comment by konradzdeb** [comment]
That's a good issue and a potential quick fix. I reckon that `format_metrics_instant_data` and `format_metrics_range_data` could better handle `value` columns. It seems `format_metrics_instant_data` may have another mistake as it calls `as.integer` (is `value` column always an integer?).

https://github.com/glenn-m/promR/blob/df18f14100e13fdfc47507932619047edff10c36/R/format_metrics_data.R#L6-L23

# Potential fix

Implement destring function converting character to numeric. If there is a risk that variable is factor can check for that as well. There is a fairly popular piece of code that folk use:

```r
destring <- function(x) {
    ## convert factor to strings
    if (is.character(x)) {
        as.numeric(x)
    } else if (is.factor(x)) {
        as.numeric(levels(x))[x]
    } else if (is.numeric(x)) {
        x
    } else {
        stop("could not convert to numeric")
    }
}
```

I'm not sure if we want to account for checking for integeres to optionally have `as.integer` in that `destring` function?

**Comment by konradzdeb** [comment]
OK, had a further look at it and provided a function destringing values and returning numeric. RE `complex` type. Is there actually,  possibility for `complex` values to be returned is `complex` not only applicable to where imaginary numbers appear?

https://github.com/konradzdeb/promR/blob/717b74bac6c0b2c3e4a6b9a3a1fc365364885a16/R/format_metrics_data.R#L100-L119

**Comment by glenn-m** [comment]
I think you're right, it looks like `numeric` can handle scientific notation so numeric it is!
