### ISSUE TITLE
Improve testing using httptest

### ISSUE THREAD

**Issue by konradzdeb** [glenn-m/promR#33]
[`httptest`](https://github.com/nealrichardson/httptest) offers a dedicated environment for testing functions that wrap APIs. I reckon we should consider this instead of faffing around trying to mock/wrap `httr::GET`. It seems that a substantial effort was put in that package to facilitate the development of testing and vignette generation. We would, in effect, swap one dependency for another `mockery` -> `httptest`. It just feels cleaner to me as it was developed for that purpose and looks like a more mature development.

> httptest makes it easy to write tests for code and packages that wrap web APIs. Testing code that communicates with remote servers can otherwise be painful: things like authentication, server state, and network flakiness can make testing seem too costly to bother with. The httptest package enables you to test all of the logic on the R sides of the API in your package without requiring access to the remote service.

FYI @glenn-m

**Comment by glenn-m** [comment]
Yeah I’d say that’s a good idea. It will save us writing a lot of boiler plate with the mocking.

**Comment by konradzdeb** [comment]
Also it will be useful for building vignettes, I was thinking that this would be a problem as we would have to mock function in vignettes or create another set of static objects just for the purpose of vignette compilation and I haven’t found documentation on recommend approach to this problem whereas this httest addresses that.
