### ISSUE TITLE
Enhancement: Basic Auth

### ISSUE THREAD

**Issue by matt-gp** [glenn-m/promR#47]
Hi All,

Firstly thanks for taking the time to support this project.

Would there be an appetite to pass basic auth creds? For instance if Prometheus is hosted in Openshift/OKD it will sits behind an auth proxy.

The thinking would be if someone were to pass a username/password then try and authenticate, if these aren't present then don't use them.

Any thoughts?

Thanks

Matt

**Comment by konradzdeb** [comment]
HI @matt-gp please feel free to suggest a PR. There are some good approaches in managing authentication across R and Python worlds so I reckon it's worth exploring.
